ath_exercise:
    resource: "@AthExerciseBundle/Resources/config/routing.yml"
    prefix:   /

ath_cours:
    resource: "@AthCoursBundle/Resources/config/routing.yml"
    prefix:   /cours

ath_page:
    resource: "@AthPageBundle/Resources/config/routing.yml"
    prefix:   /

ath_user:
    resource: "@AthUserBundle/Resources/config/routing.yml"
    prefix:   /
