parameters:
#    ath_page.example.class: Ath\PageBundle\Example

services:
#    ath_page.example:
#        class: %ath_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
