student_registration:
    pattern:  /register/student
    defaults: { _controller: AthUserBundle:RegistrationStudent:register }

ath_student_del:
    pattern:  /admin/delete/student
    defaults: { _controller: AthUserBundle:ManageStudent:delete }
    
professor_registration:
    pattern:  /register/professor
    defaults: { _controller: AthUserBundle:RegistrationProfessor:register }
    
ath_professor_del:
    pattern:  /admin/delete/professor
    defaults: { _controller: AthUserBundle:ManageProfessor:delete }
    
administrator_registration:
    pattern:  /register/administrator
    defaults: { _controller: AthUserBundle:RegistrationAdministrator:register }
    
ath_classe_add:
    pattern:  /register/classe
    defaults: { _controller: AthUserBundle:RegistrationClasse:register }
    
ath_classe_edit:
    pattern:  /admin/edit/classe/{id}
    defaults: { _controller: AthUserBundle:RegistrationClasse:edit }
    requirements:
      id: \d+

ath_classe_del:
    pattern:  /admin/delete/classe/{id}
    defaults: { _controller: AthUserBundle:RegistrationClasse:deleteClasse }
    requirements:
      id: \d+