ath_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AthUserBundle:Default:index }

student_registration:
    pattern:  /register/student
    defaults: { _controller: AthUserBundle:RegistrationStudent:register }

professor_registration:
    pattern:  /register/professor
    defaults: { _controller: AthUserBundle:RegistrationProfessor:register }

administrator_registration:
    pattern:  /register/administrator
    defaults: { _controller: AthUserBundle:RegistrationAdministrator:register }
