parameters:
#    ath_user.example.class: Ath\UserBundle\Example

services:
#    ath_user.example:
#        class: %ath_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
